In [1]:
import numpy

In [ ]:
Myarray = numpy.array([[5,8,3,7]])
twodarray = numpy.array ([[5,8,3,7],[1,2,3,4],[9,8,7,6]])
print(Myarray)
print(twodarray)

[[5 8 3 7]]
[[5 8 3 7]
 [1 2 3 4]
 [9 8 7 6]]


In [4]:
import numpy as np
x = np.arange(1,13)
np.split(x,4)
np.split(x,6)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

In [6]:
np.__version__

'2.5.3'

In [8]:
oneD = np.array([1,2,3,4,5])
oneD = np.array(range(1,6))
print(oneD)

print(oneD.ndim)
print(oneD.shape)
print(oneD.size)
print(oneD.itemsize)
print(oneD.dtype)

[1 2 3 4 5]
1
(5,)
5
8
int64


In [13]:
twoD = np.array([[1,2,3,4,5],[5,8,9,7,6]])
print(twoD)

print(twoD.ndim)
print(twoD.shape)
print(twoD.size)
print(twoD.itemsize)
print(twoD.dtype)

[[1 2 3 4 5]
 [5 8 9 7 6]]
2
(2, 5)
10
8
int64


In [14]:
threeD =np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(threeD)

#Attributes of array
print(threeD.ndim) #Dimensio of the arrray
print(threeD.shape) #shape of the array in roew or column 
print(threeD.size) # number of elements in the numpy array
print(threeD.itemsize) #size in bytes in the numpy array
print(threeD.dtype) #data type of the elements in numpty array

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)
9
8
int64


In [2]:
import numpy as np

In [3]:
#Two dimensional array
x=np.ones((5,4),dtype=float) #1st attributes is shape of the array ....2nd is type of the array
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
# Faster than list
import numpy as np
import time

L1 = range(1, 100000)
L2 = range(1, 100000)

A1 = np.array(L1)
A2 = np.array(L2)

# Operation to be performed on the list
start = time.time()

z = zip(L1, L2)
result1 = [x + y for x, y in z]

end = time.time()

print("List time:", (end - start) * 1000, "ms")


# Operation to be performed on NumPy array
start1 = time.time()

result2 = A1 + A2

end1 = time.time()

print("NumPy time:", (end1 - start1) * 1000, "ms")

List time: 48.0198860168457 ms
NumPy time: 14.054298400878906 ms


In [2]:
import numpy as np

In [3]:
x=np.random.rand(3,4)
print(x)

[[0.2790387  0.41576087 0.20867664 0.25087273]
 [0.37148384 0.93474283 0.35358706 0.46516847]
 [0.9752469  0.35524837 0.75609781 0.03653242]]


In [4]:
# create  a matrix of 3 x 4 of random number and find its maximun and minimum
import numpy as np

# Create a 3 x 4 matrix of random numbers
matrix = np.random.randint(1, 100, size=(3, 4))

print("Matrix:")
print(matrix)

# Find maximum and minimum
maximum = np.max(matrix)
minimum = np.min(matrix)

print("Maximum:", maximum)
print("Minimum:", minimum)


Matrix:
[[84 43 58 58]
 [67 43 38 66]
 [ 8 52 31 37]]
Maximum: 84
Minimum: 8


In [2]:
import numpy as np

In [3]:
y= np.array([[1,2,3],[4,5,6],[7,8,9],[4,4,4]])
print(y)
y[-3:-1]

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 4 4]]


array([[4, 5, 6],
       [7, 8, 9]])

In [2]:
import numpy as np
arr = np.array([1,2,3,4])
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
f=arr[[1,2]]
f1=arr1[[0,1],[1,2]]
f[0]=500
print(arr)
print(f)
print(f1)
print(f.base)
print(f1.base)

[1 2 3 4]
[500   3]
[2 7]
None
None


In [5]:
import numpy as np

In [6]:
x= np.arange(1,10)
np.split(x,[2,2,2])

[array([1, 2]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([3, 4, 5, 6, 7, 8, 9])]

In [9]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[3,3,3]])
x*y


array([[ 2,  4,  6],
       [12, 15, 18]])

In [10]:
x-y

array([[-1,  0,  1],
       [ 1,  2,  3]])

In [11]:
x/y

array([[0.5       , 1.        , 1.5       ],
       [1.33333333, 1.66666667, 2.        ]])